[package]
edition = "2021"
name    = "ucs01-relay-api"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
cosmwasm-schema   = { version = "2.0.0" }
cosmwasm-std      = { version = "2.0.0", features = ["stargate"] }
ethabi            = { workspace = true }
go-parse-duration = { workspace = true }
prost             = { workspace = true }
protos            = { workspace = true }
serde             = { workspace = true }
serde-json-wasm   = { workspace = true }
serde-utils       = { workspace = true }
sha2              = { workspace = true }
thiserror         = { workspace = true }
token-factory-api = { workspace = true }
unionlabs         = { workspace = true }
