[package]
name    = "voyager-proof-module-cosmwasm"
readme  = "README.md"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
clap           = { workspace = true, features = ["derive"] }
cometbft-rpc   = { workspace = true }
embed-commit   = { workspace = true }
ibc-union-spec = { workspace = true, features = ["serde"] }
jsonrpsee      = { workspace = true, features = ["macros", "server", "tracing"] }
prost          = { workspace = true }
protos         = { workspace = true }
serde          = { workspace = true, features = ["derive"] }
serde_json     = { workspace = true }
tokio          = { workspace = true }
tracing        = { workspace = true }
unionlabs      = { workspace = true }
voyager-sdk    = { workspace = true }
