[package]
name = "ucs03-zkgm-msg"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
token-factory-api = { workspace = true }
cosmwasm-std = { version = "1.5" }
cosmwasm-schema = { version = "1.5" }
enumorph = { workspace = true }

[lints]
workspace = true
