[package]
name    = "upgradable"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-event = { workspace = true }
cosmwasm-std   = { workspace = true, features = [] }
embed-commit   = { workspace = true }
frissitheto    = { workspace = true }
schemars       = { workspace = true, optional = true }
serde          = { workspace = true, features = ["derive"] }
serde-utils    = { workspace = true }
serde_json     = { workspace = true }
thiserror      = { workspace = true }

[features]
default = []

library  = []
schemars = ["dep:schemars"]
