[package]
name    = "tendermint-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/ibc-union/lightclient/tendermint/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbft-types                = { workspace = true, features = ["hash"] }
cosmwasm-std                  = { workspace = true, features = ["abort", "iterator"] }
embed-commit                  = { workspace = true }
frissitheto                   = { workspace = true }
ibc-union-light-client        = { workspace = true }
ibc-union-msg                 = { workspace = true }
ics23                         = { workspace = true }
serde                         = { workspace = true, features = ["derive"] }
sha2                          = { workspace = true }
tendermint-light-client-types = { workspace = true, features = ["ethabi", "serde", "bincode"] }
tendermint-verifier           = { workspace = true }
thiserror                     = { workspace = true }
unionlabs                     = { workspace = true }

[dev-dependencies]
base64      = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }


[features]
library = []

bls = ["cosmwasm-std/cosmwasm_2_1"]
