[package]
name    = "starknet-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = "LICENSE"
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std                = { workspace = true }
embed-commit                = { workspace = true }
ethereum-light-client       = { workspace = true }
frissitheto                 = { workspace = true }
ibc-union-light-client      = { workspace = true }
starknet-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
starknet-storage-verifier   = { workspace = true }
starknet-types              = { workspace = true }
starknet-verifier           = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true }
