[package]
name    = "cometbls-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/ibc-union/lightclient/cometbls/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbls-groth16-verifier   = { workspace = true }
cometbls-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
cosmwasm-std                = { workspace = true, features = ["abort", "iterator"] }
embed-commit                = { workspace = true }
frissitheto                 = { workspace = true }
ibc-union-light-client      = { workspace = true }
ibc-union-msg               = { workspace = true }
ics23                       = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64      = { workspace = true }
hex-literal = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }


[features]
library = []
