[package]
edition = "2024_07"
name    = "loopback_light_client"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_bytes = { workspace = true }
alexandria_math  = { workspace = true }
ibc              = { workspace = true }
starknet         = { workspace = true }

[dev-dependencies]
assert_macros = "2.13.1"
snforge_std   = { workspace = true }

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
