[package]
name    = "union-test"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }


[package.metadata.crane]
test-include = ["tools/union-test/config.jsonc", "tools/union-test/tests/config.json"]

[dependencies]
alloy              = { workspace = true, features = ["contract", "network", "providers", "signers", "signer-local", "rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
alloy-sol-types    = { workspace = true }
bip32              = { workspace = true }
cometbft-rpc       = { workspace = true }
concurrent-keyring = { workspace = true }
cosmos-client      = { workspace = true }
cosmos-sdk-event   = { workspace = true }
cosmwasm-std       = { workspace = true }
cw20               = { workspace = true }
embed-commit       = { workspace = true }
hex-literal        = { workspace = true }
ibc-solidity       = { workspace = true, features = ["serde", "rpc"] }
ibc-union-spec     = { workspace = true }
jsonrpsee          = { workspace = true, features = ["tracing", "ws-client", "http-client"] }
lst                = { workspace = true, features = ["library"] }
prost              = { workspace = true }
protos             = { workspace = true }
rand               = { workspace = true, features = ["default"] }
regex              = "1"
serde              = { workspace = true }
serde-utils        = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
ucs03-zkgm         = { workspace = true, features = ["library"] }
unionlabs          = { workspace = true }
voyager-sdk        = { workspace = true }

[dev-dependencies]
lst-staker         = { workspace = true, features = ["library"] }
tokio              = { workspace = true, features = ["macros", "rt"] }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
