[package]
name = "hubble"
version = "0.1.0"
edition = "2021"
[lib]
name = "hubble"
path = "src/lib.rs"

[[bin]]
name = "hubble"
path = "src/main.rs"

[dependencies]
graphql_client = { version = "0.13.0",  features = ["reqwest-rustls", "reqwest", "reqwest-blocking"] }
tendermint-rpc = { workspace = true, features = ["http", "http-client", "hyper-rustls", "tokio"] }
tendermint = { workspace = true, features = ["std"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "^0.11", features = ["json", "blocking"] }
serde_json = { version = "1.0" }
color-eyre = "0.6.2"
clap = { version = "4.4.0", features = ["derive", "env"] }
url = { version = "2.4.1", features = ["serde"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
futures = "0.3.28"
prometheus = { version = "0.13.3", features = ["process"] }
lazy_static = "1.4.0"
axum = { version = "0.6.20", features = ["macros"] }
