[package]
edition = "2024.beta"
name    = "owned_vault"
published-at = "0x43bd9824d09fbc994b2ecded5c31805b63166687c24d325c2541ee7e3f216c02"

[dependencies]
ibc = { local = "../ibc" }

[addresses]
ibc         = "0x8c7414ef89a6cb00a43c60027316ae450b642eca67a5a9d14fe34135e2edea05"
owned_vault = "0x0"

[dev-addresses]
ibc         = "0x1111"
owned_vault = "0x3333"
