[package]
name    = "state-lens-ics23-ics23-light-client"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbls-light-client                     = { workspace = true }
cosmwasm-std                              = { workspace = true }
embed-commit                              = { workspace = true }
frissitheto                               = { workspace = true }
ibc-union-light-client                    = { workspace = true }
ibc-union-msg                             = { workspace = true }
ibc-union-spec                            = { workspace = true }
ics23                                     = { workspace = true }
state-lens-ics23-ics23-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
state-lens-light-client-types             = { workspace = true, features = ["ethabi", "bincode"] }
tendermint-light-client-types             = { workspace = true, features = ["ethabi"] }
thiserror                                 = { workspace = true }
unionlabs                                 = { workspace = true, features = ["ethabi", "bincode"] }

[dev-dependencies]
hex-literal = { workspace = true }
serde_json  = { workspace = true }

[features]
default = []
# enabling this feature disables exposing the entrypoints and setting `#[global_allocator]`
library = []
