[package]
name    = "mpc-coordinator"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
clap               = { workspace = true, features = ["derive"] }
hex                = { workspace = true }
mpc-shared         = { workspace = true }
pgp                = "0.13"
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["full"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "tracing-log"] }
