[package]
authors = ["Union Labs"]
edition = "2021"
name    = "near-ibc-tests"
version = "0.1.0"

[dependencies]
anyhow                    = "1.0"
borsh                     = { workspace = true, features = ["borsh-derive"] }
ibc-vm-rs.workspace       = true
near-contract-standards   = "5.1.0"
near-sdk                  = { workspace = true }
near-sdk-contract-tools   = { workspace = true }
near-units                = "0.2.0"
near-workspaces           = { git = "https://github.com/unionlabs/near-workspace-rs", branch = "near-ibc", default-features = false }
serde.workspace           = true
serde_json.workspace      = true
tokio                     = { version = "1.18.1", features = ["full"] }
unionlabs.workspace       = true
# near-primitives = { git = "https://github.com/near/nearcore" }
base64                  = { workspace = true }
env_logger              = "0.9"
hex.workspace           = true
near-crypto             = "0.20"
near-jsonrpc-client     = "0.8"
near-jsonrpc-primitives = "0.20"
near-primitives         = "0.20"
near-primitives-core    = { version = "0.21" }
near-store              = { git = "https://github.com/near/nearcore" }
sha2                    = { workspace = true }
# Pinning to 0.3.36 here since they introduced a new trait in the minor version of semver..
time = { version = "0.3.36", features = ["parsing", "serde"] }
