base = "result"
exclude = [
  '.woff2$',
  '^https://statesync.testnet.bonlulu.uno/',
  '^https://grpc.testnet.bonlulu.uno/',
  '^http://myserver.com:1111/',
  '^https://x.com/',
]

exclude_all_private = true
