[package]
name    = "voyager-client-module-ethereum"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
beacon-api-types            = { workspace = true, features = ["serde"] }
embed-commit                = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
unionlabs                   = { workspace = true }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }
