[package]
name    = "on-zkgm-call-proxy"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
cosmwasm-std   = { workspace = true }
depolama       = { workspace = true }
embed-commit   = { workspace = true }
frissitheto    = { workspace = true }
schemars       = { workspace = true, optional = true, features = ["derive"] }
serde          = { workspace = true, features = ["derive"] }
thiserror      = { workspace = true }
ucs03-zkgmable = { workspace = true }

[dev-dependencies]
ibc-union-spec       = { workspace = true }
unionlabs-primitives = { workspace = true }

[features]
default  = []
library  = []
schemars = ["dep:schemars", "ucs03-zkgmable/schemars"]
