[package]
name    = "trusted-mpt-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std                   = { workspace = true, features = ["abort"] }
embed-commit                   = { workspace = true }
ethereum-light-client          = { workspace = true, features = ["library"] }
ethereum-light-client-types    = { workspace = true }
evm-storage-verifier           = { workspace = true }
frissitheto                    = { workspace = true }
ibc-union-light-client         = { workspace = true }
ibc-union-msg                  = { workspace = true }
serde                          = { workspace = true, features = ["derive"] }
thiserror                      = { workspace = true }
trusted-mpt-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
unionlabs                      = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64     = { workspace = true }
hex        = { workspace = true }
serde_json = { workspace = true }

[features]
library = []
