[package]
name    = "ibc-union-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
access-managed = { workspace = true }
cosmwasm-std   = { workspace = true }
depolama       = { workspace = true }
frissitheto    = { workspace = true }
ibc-union      = { workspace = true, features = ["library"] }
ibc-union-msg  = { workspace = true }
ibc-union-spec = { workspace = true }
macros         = { workspace = true }
pausable       = { workspace = true }
schemars       = { workspace = true, optional = true }
serde          = { workspace = true }
serde-utils    = { workspace = true }
thiserror      = { workspace = true }
unionlabs      = { workspace = true }
upgradable     = { workspace = true }

[features]
default = []

schemars = ["dep:schemars", "upgradable/schemars", "pausable/schemars"]
