[package]
edition = "2024.beta"
name    = "escrow_vault"

[dependencies]
ibc = { local = "../ibc" }

[addresses]
escrow_vault = "_"
ibc          = "_"

[dev-addresses]
escrow_vault = "0x4444"
ibc          = "0x1111"
