[package]
edition      = "2024.beta"
name         = "escrow_vault"
published-at = "0x4a936bdfc038e78eea25fd587aa0b99d492416841d166b2db64ba5ac13311577"

[dependencies]
ibc = { local = "../ibc" }

[addresses]
escrow_vault = "0x0"
ibc          = "0x8c7414ef89a6cb00a43c60027316ae450b642eca67a5a9d14fe34135e2edea05"

[dev-addresses]
escrow_vault = "0x4444"
ibc          = "0x1111"
