[package]
edition = "2024.beta"
name    = "zkgm"

[dependencies]
escrow_vault = { local = "../escrow_vault" }
ibc          = { local = "../ibc" }
owned_vault  = { local = "../owned_vault" }

[addresses]
escrow_vault = "0xf8e63bc4e2c18dd8309b2b57e007bd51f8b4968ab3c29d8dd0849d2a57aa3a0a"
ibc          = "0x2931df05284a3cfc5c38fb5d67273285855bf03e6926e3a6e1f68f9757a3d7d7"
owned_vault  = "0x87f72d8b99714f31b54adb0305747ac7a2f667a71c2d0d3ad240e74d580f5373"
zkgm         = "0x0"

[dev-addresses]
escrow_vault = "0x4444"
ibc          = "0x1111"
owned_vault  = "0x3333"
zkgm         = "0x2222"
