[package]
name    = "linea-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std             = { workspace = true, features = ["abort"] }
ethereum-light-client    = { workspace = true, features = ["mainnet", "library"] }
gnark-mimc               = { workspace = true }
ics008-wasm-client       = { workspace = true }
linea-light-client-types = { workspace = true, features = ["proto"] }
linea-verifier           = { workspace = true }
linea-zktrie             = { workspace = true }
protos                   = { workspace = true }
thiserror                = { workspace = true }
unionlabs                = { workspace = true, features = ["ethabi", "stargate"] }

[dev-dependencies]
base64     = { workspace = true }
hex        = { workspace = true }
serde_json = { workspace = true }
