[package]
name    = "voyager-state-module-sui"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
clap            = { workspace = true, features = ["derive"] }
embed-commit    = { workspace = true }
ibc-union-spec  = { workspace = true, features = ["serde"] }
jsonrpsee       = { workspace = true, features = ["macros", "server", "tracing"] }
move-core-types = { workspace = true }
reqwest         = { workspace = true, features = ["json"] }
serde           = { workspace = true, features = ["derive"] }
serde-utils     = { workspace = true }
serde_json      = { workspace = true }
sui-sdk         = { workspace = true }
sui-utils       = { workspace = true }
tokio           = { workspace = true }
tracing         = { workspace = true }
unionlabs       = { workspace = true, features = ["bcs"] }
voyager-sdk     = { workspace = true }
