[package]
name    = "ucs03-zkgm"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
alloy                         = { workspace = true, features = ["sol-types"] }
cosmwasm-schema               = { workspace = true }
cosmwasm-std                  = { workspace = true }
cw-storage-plus               = { workspace = true }
ethabi                        = { workspace = true }
ibc-union-msg                 = { workspace = true }
ibc-union-spec                = { workspace = true, features = ["serde"] }
serde                         = { workspace = true, features = ["derive"] }
thiserror                     = { workspace = true }
token-factory-api             = { workspace = true }
ucs03-zkgm-token-minter-api   = { workspace = true }
unionlabs                     = { workspace = true, features = ["ethabi", "schemars"] }
unionlabs-cosmwasm-upgradable = { workspace = true }

[dev-dependencies]
hex         = { workspace = true }
hex-literal = { workspace = true }
serde_json  = { workspace = true }
