[package]
name    = "ibc-union-ucs03-zkgm"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
alloy             = { workspace = true, features = ["sol-types"] }
base58            = { version = "0.2" }
cosmwasm-schema   = { version = "1.5" }
cosmwasm-std      = { version = "1.5" }
cw-storage-plus   = { version = "1.2" }
ethabi            = { workspace = true }
ibc-union-msg     = { workspace = true }
ibc-union-spec    = { workspace = true, features = ["serde"] }
serde             = { workspace = true, features = ["derive"] }
thiserror         = { workspace = true }
token-factory-api = { workspace = true }
unionlabs         = { workspace = true, features = ["ethabi"] }
ucs03-zkgm-msg = { workspace = true }

[dev-dependencies]
hex        = { workspace = true }
serde_json = { workspace = true }
