[package]
name    = "ucs03-zkgm"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
alloy                       = { workspace = true, features = ["sol-types"] }
cosmwasm-schema             = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["cosmwasm_1_2"] }
cw-storage-plus             = { workspace = true }
embed-commit                = { workspace = true }
ethabi                      = { workspace = true }
frissitheto                 = { workspace = true }
ibc-union-msg               = { workspace = true }
ibc-union-spec              = { workspace = true, features = ["serde", "ethabi"] }
serde                       = { workspace = true, features = ["derive"] }
serde-json-wasm             = "1.0"
thiserror                   = { workspace = true }
token-factory-api           = { workspace = true }
ucs03-zkgm-token-minter-api = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi", "schemars"] }


[dev-dependencies]
cw-multi-test     = { version = "2.3", features = ["cosmwasm_2_2"] }
cw20              = "2.0.0"
cw20-base         = { workspace = true }
cw20-token-minter = { workspace = true }
hex               = { workspace = true }
hex-literal       = { workspace = true }
serde_json        = { workspace = true }
