[package]
name    = "voyager-proof-module-movement"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
aptos-move-ibc    = { workspace = true }
aptos-rest-client = { workspace = true }
aptos-types       = { workspace = true }
clap              = { workspace = true, features = ["derive"] }
ibc-union-spec    = { workspace = true }
jsonrpsee         = { workspace = true, features = ["macros", "server", "tracing"] }
reqwest           = { workspace = true, features = ["json"] }
serde             = { workspace = true, features = ["derive"] }
serde_json        = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
unionlabs         = { workspace = true }
voyager-message   = { workspace = true }
voyager-vm        = { workspace = true }
