[package]
edition = "2021"
name    = "voyager-consensus-module-ethereum"
version = "0.1.0"

[dependencies]
alloy                       = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
beacon-api                  = { workspace = true }
beacon-api-types            = { workspace = true, features = ["serde"] }
bitvec                      = { workspace = true }
chain-utils                 = { workspace = true }
enumorph                    = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["serde"] }
futures                     = { workspace = true }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
macros                      = { workspace = true }
num-bigint                  = { workspace = true }
prost                       = { workspace = true }
protos                      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
thiserror                   = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
unionlabs                   = { workspace = true }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
