[package]
name    = "lst-staker"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
cosmwasm-event     = { workspace = true }
cosmwasm-std       = { workspace = true }
cw-account         = { workspace = true, features = ["library"] }
cw-utils           = { workspace = true }
depolama           = { workspace = true, features = ["iterator"] }
embed-commit       = { workspace = true }
frissitheto        = { workspace = true }
lst                = { workspace = true, features = ["library"] }
schemars           = { workspace = true, optional = true, features = ["derive"] }
serde              = { workspace = true, features = ["derive"] }
thiserror          = { workspace = true }
unionlabs-encoding = { workspace = true, features = ["bincode"] }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default  = []
library  = []
schemars = ["dep:schemars"]
