[package]
name    = "voyager-proof-module-parlia"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy                     = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "reqwest-rustls-tls", "provider-ws"] }
embed-commit              = { workspace = true }
ibc-union-spec            = { workspace = true, features = ["serde"] }
jsonrpsee                 = { workspace = true, features = ["macros", "server", "tracing"] }
parlia-light-client-types = { workspace = true, features = ["serde"] }
serde                     = { workspace = true, features = ["derive"] }
serde_json                = { workspace = true }
tokio                     = { workspace = true }
tracing                   = { workspace = true }
unionlabs                 = { workspace = true, features = ["ethabi"] }
voyager-sdk               = { workspace = true }
