[package]
name         = "ibc-proto"
version      = "0.29.0"
authors      = ["Informal Systems <hello@informal.systems>"]
edition      = "2021"
license      = "Apache-2.0"
repository   = "https://github.com/cosmos/ibc-proto-rs"
readme       = "README.md"
categories   = ["cryptography::cryptocurrencies", "encoding", "no-std"]
keywords     = ["blockchain", "cosmos", "tendermint", "ibc", "proto"]
exclude      = ["definitions", "tools"]
description  = """
    ibc-proto provides Cosmos SDK & IBC Protocol Buffers definitions
"""

# [workspace]
# members = [
#     ".",
#     "tools/proto-compiler"
# ]

[lib]
name    = "ibc_proto"
path    = "src/lib.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost           = { version = "0.11", default-features = false }
bytes           = { version = "1.2",  default-features = false }
tonic           = { version = "0.9",  default-features = false, optional = true }
serde           = { version = "1.0",  default-features = false }
schemars        = { version = "0.8",  optional = true }
subtle-encoding = { version = "0.5",  default-features = false }
base64          = { version = "0.21", default-features = false, features = ["alloc"] }
flex-error      = { version = "0.4",  default-features = false }

## for codec encode or decode
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["full"],   optional = true }
scale-info         = { version = "2.1.2", default-features = false, features = ["derive"], optional = true }

## for borsh encode or decode
borsh = { version = "0.10.0", default-features = false, optional = true }

[dependencies.tendermint-proto]
version          = "0.30"
default-features = false

[features]
default            = ["std", "client"]
std                = []
client             = ["std", "tonic", "tonic/codegen", "tonic/transport", "tonic/prost"]
json-schema        = ["std", "schemars"]
server             = ["std", "tonic", "tonic/codegen", "tonic/transport", "tonic/prost"]
parity-scale-codec = ["dep:parity-scale-codec", "dep:scale-info"]
borsh              = ["dep:borsh"]
