[package]
name    = "base-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = "LICENSE"
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base-light-client-types     = { workspace = true, features = ["ethabi", "bincode"] }
base-verifier               = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
embed-commit                = { workspace = true }
ethereum-light-client       = { workspace = true, features = ["library"] }
ethereum-light-client-types = { workspace = true, features = ["ethabi"] }
frissitheto                 = { workspace = true }
ibc-union-light-client      = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true }
