[package]
name    = "state-lens-ics23-mpt-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cometbls-light-client                   = { workspace = true, features = ["library"] }
cosmwasm-std                            = { workspace = true }
embed-commit                            = { workspace = true }
ethereum-light-client-types             = { workspace = true, features = ["ethabi", "bincode"] }
evm-storage-verifier                    = { workspace = true }
frissitheto                             = { workspace = true }
ibc-union-light-client                  = { workspace = true }
ibc-union-msg                           = { workspace = true }
ibc-union-spec                          = { workspace = true }
ics23                                   = { workspace = true }
rlp                                     = { workspace = true }
state-lens-ics23-mpt-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
state-lens-light-client-types           = { workspace = true, features = ["ethabi", "bincode"] }
thiserror                               = { workspace = true }
unionlabs                               = { workspace = true, features = ["ethabi", "bincode"] }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = []

library = []
