[package]
name    = "parlia-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = "LICENSE"
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std              = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
depolama                  = { workspace = true }
embed-commit              = { workspace = true }
evm-storage-verifier      = { workspace = true }
frissitheto               = { workspace = true }
ibc-union-light-client    = { workspace = true }
parlia-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
parlia-types              = { workspace = true, features = ["bincode"] }
parlia-verifier           = { workspace = true }
thiserror                 = { workspace = true }
unionlabs                 = { workspace = true }
