[package]
name = "union-ethereum-lc"
version = "0.1.0"
authors = ["UnionFi Developers"]
edition = "2021"
publish = false
license = "BSL-1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
eth-minimal = [ "ethereum-verifier/config-minimal" ]

[dependencies]
bytes = { version = "1.2.1", default-features = false }
cosmwasm-schema = "1.2.0"
cosmwasm-std = { version = "1.2.0", default-features = false, features = ["abort"] }
ethabi = { version = "18.0.0", default-features = false }
ethereum-verifier = { path = "../../lib/ethereum-verifier", default-features = false }
hex = { version = "0.4", default-features = false }
ibc = { version = "0.37.0", default-features = false, features = [ "serde" ] }
prost = { version = "0.11", default-features = false }
protos = { path = "../../generated/rust", default-features = false }
rlp = { version = "0.5.2", default-features = false }
schemars = { version = "0.8.3", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde-json-wasm = { version = "*", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
ssz-rs = { package = "ssz_rs", git = "https://github.com/unionfi/ssz-rs", rev = "657972fca78fb8bbb68ad25aee91166d62fe6e85", default-features = false, features = [ "serde" ] }
thiserror = { version = "1.0.26", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }
wasm-light-client-types = { path = "../wasm-light-client-types" }

[dev-dependencies]
base64 = "0.21"
serde_json = "1"
