[package]
name = "ethereum-light-client"
version = "0.1.0"
authors = ["Union Labs"]
edition = "2021"
publish = false
license = "BSL-1.1"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = { version = "1.2.1", default-features = false }
cosmwasm-std = { version = "1.3.0", default-features = false, features = ["abort"] }
ethabi = { version = "18.0.0", default-features = false }
ethereum-verifier = { workspace = true }
hex = { version = "0.4", default-features = false }
prost = { version = "0.11", default-features = false }
protos = { workspace = true, default-features = false }
rlp = { version = "0.5.2", default-features = false }
schemars = { version = "0.8.3", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde-json-wasm = { version = "1.0.0", default-features = false }
sha3 = { version = "0.10.8", default-features = false }
thiserror = { version = "1.0.26", default-features = false }
tiny-keccak = { version = "2.0.2", default-features = false, features = ["keccak"] }

ics008-wasm-client = { workspace = true }
unionlabs = { workspace = true, default-features = false }

[dev-dependencies]
# ibc = { version = "0.37.0", default-features = false, features = [ "serde" ] }
unionlabs = { workspace = true, features = ["std"] }
lazy_static = "1.4.0"
base64 = "0.21"
serde_json = "1"
hex-literal = "0.4.1"
protos = { workspace = true, default-features = false, features = ["proto_full", "std"] }

[features]
default = ["mainnet"]
minimal = []
mainnet = []
