[package]
authors      = ["Union Labs"]
edition      = "2021"
license-file = { workspace = true }
name         = "ethereum-light-client"
publish      = false
version      = "0.1.0"

[lints]
workspace = true

[package.metadata.crane]
test-include = ["light-clients/ethereum-light-client/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
alloy-core         = { workspace = true }
bytes              = { workspace = true }
cosmwasm-std       = { workspace = true, features = ["abort"] }
ethereum-verifier  = { workspace = true }
hex                = { workspace = true }
ics008-wasm-client = { workspace = true }
prost              = { workspace = true }
protos             = { workspace = true }
rlp                = { workspace = true }
schemars           = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-json-wasm    = { workspace = true }
serde_json         = { workspace = true, optional = true }
sha3               = { workspace = true }
thiserror          = { workspace = true }
tiny-keccak        = { workspace = true, features = ["keccak"] }
unionlabs          = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64      = { workspace = true }
hex-literal = { workspace = true }
lazy_static = "1.4.0"
protos      = { workspace = true, features = ["proto_full", "std"] }
serde-utils = { workspace = true }
serde_json  = { workspace = true }
unionlabs   = { workspace = true, features = ["std"] }

[features]
default = ["mainnet"]

mainnet = []
minimal = []

# enabling this feature disables exposing the entrypoints and setting `#[global_allocator]`
library = []

# exposes some useful testing utilities
test-utils = ["dep:serde_json"]
