[package]
name    = "attested-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
access-manager-types        = { workspace = true }
attested-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
bincode                     = { workspace = true, features = ["derive"] }
cosmwasm-std                = { workspace = true }
depolama                    = { workspace = true, features = ["iterator"] }
embed-commit                = { workspace = true }
frissitheto                 = { workspace = true }
ibc-union-light-client      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde-utils                 = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64        = { workspace = true }
ed25519-dalek = { workspace = true, features = ["default"] }
hex           = { workspace = true }
hex-literal   = { workspace = true }
serde_json    = { workspace = true }
unionlabs     = { workspace = true, features = ["test-utils"] }

[features]
library = []
