[package]
name    = "voyager-finality-module-berachain"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy            = { workspace = true, features = ["rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "reqwest-rustls-tls", "provider-ws"] }
beacon-api-types = { workspace = true, features = ["serde", "ssz"] }
cometbft-rpc     = { workspace = true }
embed-commit     = { workspace = true }
jsonrpsee        = { workspace = true, features = ["macros", "server", "tracing"] }
serde            = { workspace = true, features = ["derive"] }
tokio            = { workspace = true }
tracing          = { workspace = true }
unionlabs        = { workspace = true, features = ["ssz"] }
voyager-sdk      = { workspace = true }
