[package]
edition = "2021"
name    = "voyager-chain-module-ethereum"
version = "0.1.0"

[dependencies]
beacon-api         = { workspace = true }
chain-utils        = { workspace = true }
enumorph           = { workspace = true }
alloy             = { workspace = true }
futures            = { workspace = true }
jsonrpsee          = { workspace = true, features = ["macros", "server", "tracing"] }
macros             = { workspace = true }
serde              = { workspace = true, features = ["derive"] }
serde-utils        = { workspace = true }
serde_json         = { workspace = true }
static_assertions  = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
unionlabs          = { workspace = true }
voyager-message    = { workspace = true }
voyager-vm         = { workspace = true }
