[package]
edition = "2021"
name    = "voyager-chain-module-ethereum"
version = "0.1.0"

[dependencies]
alloy                       = { workspace = true }
beacon-api                  = { workspace = true }
enumorph                    = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["serde"] }
futures                     = { workspace = true }
ibc-solidity                = { workspace = true }
jsonrpsee                   = { workspace = true, features = ["macros", "server", "tracing"] }
macros                      = { workspace = true }
serde                       = { workspace = true, features = ["derive"] }
serde-utils                 = { workspace = true }
serde_json                  = { workspace = true }
static_assertions           = { workspace = true }
thiserror                   = { workspace = true }
tokio                       = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }
voyager-message             = { workspace = true }
voyager-vm                  = { workspace = true }
