[package]
name    = "voyager-consensus-module-sui"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
embed-commit      = { workspace = true }
jsonrpsee         = { workspace = true, features = ["macros", "server", "tracing"] }
serde             = { workspace = true, features = ["derive"] }
thiserror         = { workspace = true }
tokio             = { workspace = true }
tracing           = { workspace = true }
unionlabs         = { workspace = true }
voyager-message   = { workspace = true }

sui_sdk = { git = "https://github.com/mystenlabs/sui", package = "sui-sdk"}
