[package]
authors = ["Union Labs"]
edition = "2021"
license = "BSL-1.1"
name    = "tendermint-light-client"
publish = false
version = "0.1.0"

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/ibc-union/light-clients/tendermint/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { workspace = true, features = ["abort", "cosmwasm_2_1", "iterator"] }
sha2         = { workspace = true }
thiserror    = { workspace = true }

cometbft-types                = { workspace = true, features = ["proto", "hash"] }
ibc-union-light-client        = { workspace = true }
ibc-union-msg                 = { workspace = true }
ics23                         = { workspace = true }
tendermint-light-client-types = { workspace = true, features = ["ethabi", "serde"] }
tendermint-verifier           = { workspace = true }
unionlabs                     = { workspace = true }
serde = { workspace = true }
hex-literal = { workspace = true }
serde-utils = { workspace = true }

[dev-dependencies]
base64      = { workspace = true }
lazy_static = "1.4.0"
serde_json  = { workspace = true }


[features]
library = []
