[package]
name    = "ucs03-zkgm-token-minter-api"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy-primitives     = { workspace = true }
alloy-sol-types      = { workspace = true }
cosmwasm-schema      = { workspace = true, optional = true }
cosmwasm-std         = { workspace = true }
enumorph             = { workspace = true }
ibc-union-spec       = { workspace = true, features = ["serde"] }
serde                = { workspace = true, features = ["derive"] }
token-factory-api    = { workspace = true }
unionlabs-primitives = { workspace = true }

[features]
default = []

std = ["cosmwasm-std/std"]

schemars = ["std", "unionlabs-primitives/schemars", "dep:cosmwasm-schema"]
