[package]
name    = "ethereum-light-client"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[package.metadata.crane]
test-include = ["cosmwasm/lightclient/ethereum/src/test"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ark-bls12-381               = { version = "0.5.0" }
ark-ec                      = { version = "0.5.0" }
ark-serialize               = { version = "0.5.0" }
beacon-api-types            = { workspace = true }
bincode                     = { workspace = true }
cosmwasm-std                = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
depolama                    = { workspace = true }
embed-commit                = { workspace = true }
ethereum-light-client-types = { workspace = true, features = ["ethabi", "bincode"] }
ethereum-sync-protocol      = { workspace = true }
evm-storage-verifier        = { workspace = true }
frissitheto                 = { workspace = true }
ibc-union-light-client      = { workspace = true }
rlp                         = { workspace = true }
thiserror                   = { workspace = true }
unionlabs                   = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
base64                       = { workspace = true }
beacon-api                   = { workspace = true }
ethereum-sync-protocol-types = { workspace = true }
hex-literal                  = { workspace = true }
protos                       = { workspace = true, features = ["proto_full", "std"] }
serde-utils                  = { workspace = true }
serde_json                   = { workspace = true }
unionlabs                    = { workspace = true, features = ["std"] }

[features]
library = []
