[package]
name    = "access-manager-tests"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[dependencies]
access-managed-example = { workspace = true }
access-manager-types   = { workspace = true }
anyhow                 = { workspace = true }
bip32                  = { workspace = true, features = ["alloc", "secp256k1"] }
bip39                  = "2.2.0"
clap                   = { workspace = true, features = ["color", "derive", "env", "error-context", "help", "suggestions"] }
cometbft-rpc           = { workspace = true }
cosmos-client          = { workspace = true }
cosmwasm-std           = { workspace = true }
embed-commit           = { workspace = true }
protos                 = { workspace = true }
serde                  = { workspace = true }
serde_json             = { workspace = true }
sha2                   = { workspace = true }
tokio                  = { workspace = true, features = ["full"] }
tracing                = { workspace = true }
tracing-subscriber     = { workspace = true }
unionlabs              = { workspace = true }
upgradable             = { workspace = true, features = ["library"] }

[lints]
workspace = true
