[package]
name    = "voyager-client-module-state-lens-ics23-ics23"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy-sol-types                           = { workspace = true }
embed-commit                              = { workspace = true }
jsonrpsee                                 = { workspace = true, features = ["macros", "server", "tracing"] }
protos                                    = { workspace = true }
serde                                     = { workspace = true, features = ["derive"] }
serde_json                                = { workspace = true }
state-lens-ics23-ics23-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
state-lens-light-client-types             = { workspace = true, features = ["serde", "ethabi", "bincode"] }
tokio                                     = { workspace = true }
tracing                                   = { workspace = true }
unionlabs                                 = { workspace = true, features = ["bcs"] }
voyager-sdk                               = { workspace = true }
