[package]
name    = "ibc-union-msg"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
access-managed       = { workspace = true }
cosmwasm-schema      = { workspace = true, optional = true }
cosmwasm-std         = { workspace = true, optional = true }
cw-orch              = { workspace = true, optional = true }
enumorph             = { workspace = true }
ibc-union-spec       = { workspace = true, features = ["serde"] }
pausable             = { workspace = true }
schemars             = { workspace = true, optional = true }
serde                = { workspace = true, features = ["derive"] }
unionlabs-primitives = { workspace = true, features = ["serde", "std"] }
upgradable           = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []

cw-orch-interface = ["schemars", "dep:cw-orch", "dep:cosmwasm-std", "dep:cosmwasm-schema"]
schemars = [
  "dep:schemars",
  "unionlabs-primitives/schemars",
  "ibc-union-spec/schemars",
  "access-managed/schemars",
  "upgradable/schemars",
  "pausable/schemars",
]
