[package]
name    = "parse-wasm-client-type"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
clap             = { workspace = true, features = ["derive", "help"] }
embed-commit     = { workspace = true }
wasm-client-type = { workspace = true }
