[package]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "parse-wasm-client-type"
publish      = false
repository   = { workspace = true }
version      = "0.1.0"

[lints]
workspace = true

[dependencies]
clap      = { workspace = true, features = ["derive", "help"] }
unionlabs = { workspace = true }
