[package]
name = "parse-wasm-client-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive", "std", "help"], default-features = false }
unionlabs = { workspace = true }
