[package]
name    = "voyager-client-module-state-lens-ics23-smt"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy                                   = { workspace = true, features = ["sol-types"] }
chain-utils                             = { workspace = true }
enumorph                                = { workspace = true }
ethereum-light-client-types             = { workspace = true, features = ["serde", "ethabi", "bincode"] }
futures                                 = { workspace = true }
jsonrpsee                               = { workspace = true, features = ["macros", "server", "tracing"] }
macros                                  = { workspace = true }
prost                                   = { workspace = true }
serde                                   = { workspace = true, features = ["derive"] }
serde-utils                             = { workspace = true }
serde_json                              = { workspace = true }
state-lens-ics23-smt-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
state-lens-light-client-types           = { workspace = true, features = ["serde", "ethabi", "bincode"] }
thiserror                               = { workspace = true }
tokio                                   = { workspace = true }
tracing                                 = { workspace = true }
tracing-subscriber                      = { workspace = true }
unionlabs                               = { workspace = true }
voyager-message                         = { workspace = true }
voyager-vm                              = { workspace = true }
