[package]
name    = "voyager-client-module-state-lens-ics23-smt"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[dependencies]
aptos-types                             = { workspace = true, features = ["serde", "bincode"] }
embed-commit                            = { workspace = true }
jsonrpsee                               = { workspace = true, features = ["macros", "server", "tracing"] }
serde                                   = { workspace = true, features = ["derive"] }
serde_json                              = { workspace = true }
state-lens-ics23-smt-light-client-types = { workspace = true, features = ["serde", "ethabi", "bincode"] }
state-lens-light-client-types           = { workspace = true, features = ["serde", "ethabi", "bincode"] }
tokio                                   = { workspace = true }
tracing                                 = { workspace = true }
unionlabs                               = { workspace = true }
voyager-sdk                             = { workspace = true }
