[package]
name    = "pausable"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cosmwasm-event = { workspace = true }
cosmwasm-std   = { workspace = true, features = [] }
depolama       = { workspace = true }
schemars       = { workspace = true, optional = true }
serde          = { workspace = true, features = ["derive"] }
thiserror      = { workspace = true }

[features]
default = []

library  = []
schemars = ["dep:schemars"]
