[package]
authors      = ["Hussein Ait Lahcen <hussein.aitlahcen@gmail.com>"]
edition      = { workspace = true }
license-file = { workspace = true }
name         = "ucs02-nft"
repository   = "https://github.com/unionlabs/union"
version      = "1.0.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["stargate"] }
cw-storage-plus = { workspace = true }
dlmalloc        = { workspace = true, features = ["global"] }
ethabi          = { workspace = true }
ics721          = { git = "https://github.com/hussein-aitlahcen/cw-ics721", rev = "dd5b7add6fdc81e633084031f8512e5e909dd42a" }
ics721-base     = { git = "https://github.com/hussein-aitlahcen/cw-ics721", rev = "dd5b7add6fdc81e633084031f8512e5e909dd42a", features = ["library"] }
serde           = { workspace = true, features = ["derive"] }
thiserror       = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
