[package]
edition = "2021"
name    = "ibc-union-solana"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
embed-commit                       = { workspace = true }
ibc-union-spec                     = { workspace = true }
pinocchio                          = "0.9.2"
pinocchio-associated-token-account = "0.2.0"
pinocchio-pubkey                   = "0.3.0"
pinocchio-system                   = "0.3.0"
pinocchio-token                    = "0.4.0"
solana-account-info                = "3.0.0"
unionlabs-primitives               = { workspace = true }

[dev-dependencies]
mollusk-svm = "0.6.1"
solana-sdk  = "3.0.0"
