[package]
name    = "devnet-utils"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
base64          = { workspace = true }
bip39           = "2.0.0"
clap            = { workspace = true, features = ["derive", "error-context", "help"] }
cosmwasm-std    = { workspace = true }
ed25519-compact = { version = "2.1.1", default-features = false, features = ["ed25519"] }
embed-commit    = { workspace = true }
hex             = { workspace = true, features = ["std"] }
strum           = { version = "0.26.1", features = ["derive"] }
tiny-hderive    = "0.3.0"
unionlabs       = { workspace = true }
