[package]
name    = "tidy"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cargo-util-schemas = "0.10.2"
cargo_metadata     = "0.23.1"
clap               = { workspace = true, features = ["derive", "default"] }
embed-commit       = { workspace = true }
regex              = "1.11.3"
toml               = { workspace = true, features = ["parse"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt"] }
