[package]
name    = "tidy"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cargo-util-schemas = "0.1.0"
cargo_metadata     = "0.18.1"
clap               = { workspace = true, features = ["derive", "default"] }
toml               = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt"] }
