[package]
name    = "sui-light-client"
version = "0.0.0"

authors    = { workspace = true }
edition    = { workspace = true }
license    = { workspace = true }
publish    = { workspace = true }
repository = { workspace = true }

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std           = { workspace = true, features = ["abort", "cosmwasm_2_1"] }
depolama               = { workspace = true }
embed-commit           = { workspace = true }
frissitheto            = { workspace = true }
ibc-union-light-client = { workspace = true }
sui-light-client-types = { workspace = true, features = ["bincode", "ethabi"] }
sui-verifier           = { workspace = true }
thiserror              = { workspace = true }
unionlabs              = { workspace = true, features = ["ethabi"] }

[dev-dependencies]
hex-literal          = { workspace = true }
serde_json           = { workspace = true }
unionlabs-primitives = { workspace = true, features = ["base64"] }

[features]
default = []

library = []
