[package]
name    = "u"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
alloy              = { workspace = true, features = ["contract", "network", "providers", "rpc", "rpc-types", "transports", "transport-http", "transport-ws", "reqwest", "provider-ws"] }
anyhow             = { workspace = true }
base64             = { workspace = true }
clap               = { workspace = true, features = ["default", "derive", "env", "error-context", "color"] }
cometbft-rpc       = { workspace = true }
create3            = { workspace = true }
deployments        = { workspace = true }
derive_more        = { workspace = true }
embed-commit       = { workspace = true }
hex                = { workspace = true }
ibc-classic-spec   = { workspace = true }
ibc-union-spec     = { workspace = true, features = ["serde"] }
jsonrpsee          = { workspace = true, features = ["client", "full", "tracing"] }
num_cpus           = "1.16"
protos             = { workspace = true, features = ["proto_full", "serde"] }
rand               = "0.8"
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
tokio              = { workspace = true, features = ["macros"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
ucs03-zkgm         = { workspace = true }
ucs04              = { workspace = true, features = ["serde"] }
unionlabs          = { workspace = true, features = ["bcs", "bincode", "ethabi", "proto", "ssz"] }
voyager-primitives = { workspace = true, features = ["serde"] }


arbitrum-light-client-types               = { workspace = true, features = ["serde", "bincode", "ethabi"] }
berachain-light-client-types              = { workspace = true, features = ["serde", "bincode", "ethabi"] }
bob-light-client-types                    = { workspace = true, features = ["serde", "bincode", "ethabi"] }
cometbls-light-client-types               = { workspace = true, features = ["serde", "bincode", "ethabi"] }
ethereum-light-client-types               = { workspace = true, features = ["serde", "bincode", "ethabi"] }
ethermint-light-client-types              = { workspace = true, features = ["serde", "bincode"] }
linea-light-client-types                  = { workspace = true, features = ["serde"] }
movement-light-client-types               = { workspace = true, features = ["serde", "bincode", "ethabi"] }
parlia-light-client-types                 = { workspace = true, features = ["bincode", "serde", "ethabi"] }
scroll-light-client-types                 = { workspace = true, features = ["serde"] }
state-lens-ics23-ics23-light-client-types = { workspace = true, features = ["serde", "ethabi"] }
state-lens-ics23-mpt-light-client-types   = { workspace = true, features = ["serde", "bincode", "ethabi"] }
state-lens-ics23-smt-light-client-types   = { workspace = true, features = ["serde", "bincode", "ethabi"] }
tendermint-light-client-types             = { workspace = true, features = ["serde", "bincode", "ethabi"] }
trusted-mpt-light-client-types            = { workspace = true, features = ["serde", "bincode", "ethabi"] }
