[package]
edition = "2024_07"
name    = "cometbls_verifier"
version = "0.1.0"

[dependencies]
garaga   = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.18.2" }
starknet = "2.11.4"

[cairo]
inlining-strategy  = 2
sierra-replace-ids = false

[dev-dependencies]
assert_macros = "2.11.4"
snforge_std   = "0.51.1"

[[target.starknet-contract]]
casm                    = true
casm-add-pythonic-hints = true
