[package]
edition = "2024_07"
name    = "zasset"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_bytes      = { workspace = true }
alexandria_encoding   = { workspace = true }
ibc                   = { workspace = true }
loopback_light_client = { workspace = true }
openzeppelin          = { workspace = true }
payments_zkp_verifier = { workspace = true }
starknet              = { workspace = true }

[dev-dependencies]
assert_macros = "2.13.1"
snforge_std   = "0.53.0-rc.0"

[[target.starknet-contract]]
build-external-contracts = [
  "payments_zkp_verifier::groth16_verifier::Groth16VerifierBN254",
  "loopback_light_client::contract::StarknetLightClient",
]
casm = true
casm-add-pythonic-hints = true

[scripts]
test = "snforge test -p zasset --include-ignored"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
