[package]
name = "zasset"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.13.1"
ibc      = { workspace = true }
loopback_light_client = { workspace = true }

[dev-dependencies]
snforge_std = "0.53.0-rc.0"
assert_macros = "2.13.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

