[package]
name    = "token-factory-api"
version = "0.0.0"

authors      = { workspace = true }
edition      = { workspace = true }
license-file = { workspace = true }
publish      = { workspace = true }
repository   = { workspace = true }

[lints]
workspace = true

[dependencies]
cosmwasm-schema = { workspace = true, optional = true }
cosmwasm-std    = { workspace = true }
enumorph        = { workspace = true }
schemars        = { workspace = true, optional = true }
serde           = { workspace = true }

[features]
default = []

std = []

schemars = ["std", "dep:schemars"]
