
name: Full end-to-end (e2e) testsuite.

on:
  workflow_call:
    secrets:
      nixbuild_token:
        required: true
      github-token:
        required: true
      org_token:
        required: true

jobs:
  build:
    uses: unionlabs/workflows/.github/workflows/build.yml@7d57fd7b5f3e0bdec18acc8a6e2f365106928dff
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GH_NIX_TOKEN }}
      org_token: ${{ secrets.GH_NIX_TOKEN }}
    with:
      filter_builds: '((.top_attr == "checks") and (.system == "x86_64-linux") and (.attr == "virtualisation-works" or .attr == "ensure-blocks" or .attr == "sepolia-runs" or .attr == "union-runs" or .attr == "epoch-completes" or .attr == "forced-set-rotation" or .attr == "upgrade-from-genesis" or .attr == "upgrade-with-tokenfactory-state"))'
