
name: Full end-to-end (e2e) testsuite.

on:
  workflow_call:
    secrets:
      nixbuild_token:
        required: true
      github-token:
        required: true

jobs:
  build:
    uses: unionlabs/workflows/.github/workflows/build.yml@e104e81267a8e17e17d14ccb86e28ff970a477cd
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.github-token }}
    with:
      filter_builds: '((.top_attr == "checks") and (.system == "x86_64-linux") and (.attr == "virtualisation-works" or .attr == "ensure-blocks" or .attr == "sepolia-runs" or .attr == "union-runs" or .attr == "epoch-completes" or .attr == "forced-set-rotation" or .attr == "upgrade-from-genesis" or .attr == "upgrade-with-tokenfactory-state"))'
