on:
  schedule:
    - cron: "20 4 * * *"
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= union.cachix.org-1:TV9o8jexzNVbM1VNBOq9fu8NK+hL6ZhOyOh0quATy+M=
            trusted-substituters = https://cache.nixos.org https://cache.garnix.io https://union.cachix.org
      - name: Fetch from Cache
        run: |
          sudo mkdir "/run/containers/30002"
          sudo mkdir "/run/containers/30003"
          sudo mkdir "/run/containers/30004"
          sudo mkdir "/run/containers/30005"
          sudo chmod 777 "/run/containers"
          sudo chmod 777 "/run/containers/30002"
          sudo chmod 777 "/run/containers/30003"
          sudo chmod 777 "/run/containers/30004"
          sudo chmod 777 "/run/containers/30005"
          ls -la /run/containers
          nix build .#checks.x86_64-linux.e2e-lst -L --option sandbox false
