name: Nightly

on:
  workflow_call:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:    
    uses: ./.github/workflows/actions/e2e
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    needs: [ build ]
    # only create an issue if it failed in a scheduled run
    if: github.event_name == "schedule" && failure()
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/templates/nightly-issue-template.md
