name: Nightly

on:
  push:
  # schedule:
  #   - cron: '0 4 * * *'

jobs:
  build:
    uses: unionlabs/workflows/.github/workflows/build.yml@679907725e8f8e800a31677bad1b0d0decc9399f
    secrets:
      nixbuild_token: ${{ secrets.nixbuild_token }}
      access-tokens: github.com=${{ secrets.GITHUB_TOKEN }}
    with:
      filter_builds: '((.top_attr == "checks") and (.system == "x86_64-linux" or .system == "aarch64-linux") and (.attr == "virtualisation-works"))'
  create-issue:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/templates/nightly-issue-template.md
